# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85864eb27af452a1772bf89b3acab8aa9cf6a06885b5f5630f320f4758d314f980ba9d7c66feee5fe2a65ad986dc98768cf6d22ddedc70103a9918736a7729de

test:
  secret_key_base: 24072edf38c7fbac06d46ae7cffd0dbae949e2409d1583ac4bed1f161393a6e0039b0a4579f05f875d5a8d5611997ab70830bdbb9e3586a8441a3758afa71966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
